# Generated by Django 3.1.7 on 2021-02-28 18:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('alphacode2', models.CharField(blank=True, db_index=True, max_length=3, null=True, unique=True)),
                ('alphacode3', models.CharField(blank=True, db_index=True, max_length=4, null=True, unique=True)),
                ('capital', models.CharField(blank=True, max_length=25, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('timezones', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None), size=1)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('flag', models.FileField(blank=True, null=True, upload_to='flag')),
                ('languages', models.JSONField(blank=True, null=True)),
                ('neighbouring_countries', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5), size=None), size=1)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
    ]
