# Generated by Django 3.1.7 on 2021-02-28 07:06

import apps.country.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('alphacode2', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('alphacode3', models.CharField(blank=True, db_index=True, max_length=4, null=True)),
                ('capital', models.CharField(blank=True, max_length=25, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone', models.JSONField(blank=True, null=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to=apps.country.models.flag_image_upload_path)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('neighbouring_countries', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
    ]
