# Generated by Django 3.1.7 on 2021-02-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='CountryInfo',
        ),
    ]
