# Generated by Django 3.1.7 on 2021-03-01 19:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryinfo',
            name='neighbouring_countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='countryinfo',
            name='timezones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), null=True, size=None),
        ),
    ]
