# Generated by Django 3.1.7 on 2021-03-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20210301_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryinfo',
            name='alphacode3',
        ),
    ]
